spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpashop?autoReconnect=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username : jpa
    password: 1q2w3e4r5t
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show-sql: true
        format_sql: true
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    org.hibernate.SQL: debug

